version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '7432:5432'

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
